"""deep-gvr readiness scaffolding."""

from .contracts import (
    AnalyticalCheck,
    AnalyticalStatus,
    Backend,
    CandidateSolution,
    CapabilityProbeResult,
    DeepGvrConfig,
    EvidenceRecord,
    ProbeStatus,
    SessionIndex,
    SessionSummary,
    SimAnalysis,
    SimDataPoint,
    SimResources,
    SimResults,
    SimSpec,
    SimTask,
    Tier1Report,
    Tier2Report,
    Tier3ClaimResult,
    VerificationReport,
    VerificationVerdict,
)
from .probes import run_capability_probes

__all__ = [
    "AnalyticalCheck",
    "AnalyticalStatus",
    "Backend",
    "CandidateSolution",
    "CapabilityProbeResult",
    "DeepGvrConfig",
    "EvidenceRecord",
    "ProbeStatus",
    "SessionIndex",
    "SessionSummary",
    "SimAnalysis",
    "SimDataPoint",
    "SimResources",
    "SimResults",
    "SimSpec",
    "SimTask",
    "Tier1Report",
    "Tier2Report",
    "Tier3ClaimResult",
    "VerificationReport",
    "VerificationVerdict",
    "run_capability_probes",
]
